Makefile.toml: Add `patina-test` task (#829)
## Description

Right now, `cargo make test` does not support common test arguments
like `-p`:

```
  error: invalid character `;` in package name: `;patina`, the first
  character must be a Unicode XID start character (most letters or `_`)

  Error while executing command, exit code: 101
```

It is useful to only against test in a given package during
development. This change proposes `cargo make test` behaving similar
to `cargo test` so users don't have to know when to switch between
the two and can use `cargo make` as their common command root.

Now something like this works:

> `cargo make test -p patina_mm -- --nocapture`

---

In the course of changing the test command, this is also fixed:

`enable_patina_tests` is a feature that is used to build test code
to execute on platforms. It can be thought of conceptually like
UEFI application testing on a given platform. It is not related
to unit testing on a host machine.

This change removes the feature from the `test` command entirely
and builds code with that feature under its own `patina-test`
task using the underlying `build` command.

Also, not all crates support `enable_patina_tests`. Previously,
you'd run into errors like this even if individual crates were
supported in the test command if the crate didn't support the
feature:

```
error: the package 'patina_adv_logger' does not contain this feature:
enable_patina_tests
```

That feature can be enabled against all workspace:

```
cargo make patina-test
```

The `all` task now includes both `test` (for host-based tests) and
`patina-tests` (for building the on-platform tests).

`patina-test` can be run against an individual package that supports
the feature. For example:

```
cargo make patina-test -p patina_macro
```

- [ ] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

- `cargo make test`
- `cargo make test -p patina_mm`
- `cargo make test -p patina_mm -- --nocapture`
- `cargo make patina-test`
- `cargo make patina-test -p patina_macro`
- `cargo make all`

## Integration Instructions

- No integration needed. But developers should review how each test
command is used.

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>