Disable default features across Patina crates to make feature dependencies explicit
**TIL:**

Behavior of `--all-features` with explicit package vs without explicit package,
```
cargo clippy --all-features --tests
workspace
  crate a(feature fa)           <--- all features defined in crate_a are enabled and built as a test binary
    crate b(feature fb)         <--- all features defined in crate_b are enabled and built as a lib

cargo clippy -p crate_a --all-features --tests
workspace
  crate a(feature fa)           <--- all features defined in crate_a are enabled and built as a test binary
    crate b(feature fb)         <--- only features selected when specifying crate_b as dependency are enabled(if non selected, default features are applied) and built as a lib
```
NOTE: --tests is nothing special here any target can be picked

**Problem:** Rust MM Supervisor avoids hidden heap allocations from dependencies
by ensuring the "alloc" feature is not enabled. Since Patina currently includes
"alloc" in its default feature set, the MM Supervisor branch had to explicitly
remove it from its default features(`default = []`) and also by not defining an
explicit `#[global_allocator]`. Because `default-features = false` only affects
a direct dependency, not transitive dependencies

Now with `default=[]` in place on patina sdk in feature/supv branch,

Before the SDK refactor, c_ptr.rs is gated as shown below. Which means trying to
run `cargo clippy --tests` did not break the build with or without
--all-features because in both cases c_ptr.rs is fully stubbed out as patina
sdk is neither built with test feature(remember this is a dependency to whatever
crate is being built) nor alloc(since we have set default=[]).

```
sdk\patina\src\lib.rs
#[cfg(any(test, feature = "alloc"))]        <----- stubbed out because patina sdk is a dependency for whatever test crate is being built right now
extern crate alloc;

#[cfg(any(test, feature = "alloc"))]        <----- stubbed out because patina sdk is a dependency for whatever test crate is being built right now
pub mod boot_services;

sdk\patina\src\boot_services\c_ptr.rs       <----- stubbed out because patina sdk is a dependency for whatever test crate is being built right now
use alloc::boxed::Box;
```

After the SDK refactor, c_ptr.rs is NOT gated. Which means trying to run `cargo
clippy --tests` will break the build with or without `--all-features` because in
both the cases c_ptr.rs is always present and `extern crate alloc` is always
absent as neither test feature(again remember this is a dependency to whatever
crate is being built) nor alloc(since we have set default=[]).

```
sdk\patina\src\lib.rs
#[cfg(any(test, feature = "alloc"))]        <----- stubbed out because patina sdk is a dependency for whatever test crate is being built right now
extern crate alloc;

pub mod base;                               <----- NOT STUBBED OUT

sdk\patina\src\base\c_ptr.rs                <----- NOT STUBBED OUT
use alloc::boxed::Box;
```

Resulting in below error:

  ```
  error[E0433]: cannot find module or crate `alloc` in this scope
 --> sdk\patina\src\base\c_ptr.rs:9:5
  |
9 | use alloc::boxed::Box;
  |     ^^^^^ use of unresolved module or unlinked crate `alloc`
  ```

While restoring the feature gate on `c_ptr` fixes this immediate issue(also done
in https://github.com/OpenDevicePartnership/patina/pull/1677), debugging feature
related failures like this is not a very pleasant experience. In particular,
`--all-features` only applies to the package being built and does not propagate
to dependencies. To some extent `cargo hack` makes it easier to run failing
command on individual packages but that brings in its own set of new challenges.
After spending a considerable amount of time untangling the dependencies and
understanding the root cause, it seems that disabling the default feature set
across all Patina crates would alleviate some of the debugging pain.

Benefits:
1. Patina crates no longer assume the presence of the `alloc` feature.
2. Crates within Patina repo are nothing special and they have to explicitly
   declare the required feature set, making feature usage easier to audit and
   maintain.
    ```
    E:\repos\patina>cargo tree -e features -p patina_ffs_extractors -e=no-dev
    patina_ffs_extractors v23.0.1 (E:\repos\patina\sdk\patina_ffs_extractors)
    ...
    ├── patina feature "default"  <----

    vs

    E:\repos\patina>cargo tree -e features -p patina_ffs_extractors -e=no-dev
    patina_ffs_extractors v23.0.1 (E:\repos\patina\sdk\patina_ffs_extractors)
    ...
    ├── patina feature "alloc"    <----
    ```
3. Rust MM Supervisor can now opt out of `alloc` without requiring any hacks.
   Please note that #[global_allocator] should still be avoided so that the
   compiler can flag any dependent code paths that require heap allocations.

This is a breaking change because existing consumers relying on Patina's default
feature set will need to explicitly enable the required features. Most existing
crates have already been updated as part of this commit.